# -Try to find Gotoblas
#
# The following are set after configuration is done: 
#  GOTOBLAS_FOUND
#  GOTOBLAS_LIBRARIES
#  GFORTRAN_LIBRARY

SET(GOTOBLAS_POSSIBLE_LIBPATHS

  /usr/lib
  /usr/local/lib
  /usr/lib64
  )

FIND_LIBRARY(GOTOBLAS_LIBRARIES

  NAMES libgoto2.so
  PATHS ${GOTOBLAS_POSSIBLE_LIBPATHS}
  )

FIND_LIBRARY(GFORTRAN_LIBRARY

  NAMES libgfortran.a
  PATHS 
  /usr/lib
  /usr/local/lib
  /usr/lib64
  
  )

IF(NOT GOTOBLAS_LIBRARIES)
  MESSAGE(WARNING "Goto2blas library not found.")
ENDIF(NOT GOTOBLAS_LIBRARIES)

IF(NOT GFORTRAN_LIBRARY)
  MESSAGE(WARNING "gfortran library for goto-blas not found.")
ENDIF(NOT GFORTRAN_LIBRARY)

IF(GOTOBLAS_LIBRARIES)
  MESSAGE(STATUS "Found Goto2blas: " ${GOTOBLAS_LIBRARIES})
  SET(GOTOBLAS_FOUND TRUE)
ELSE(GOTOBLAS_LIBRARIES)
  SET(GOTOBLAS_FOUND FALSE)
ENDIF(GOTOBLAS_LIBRARIES)

SET ( GOTOBLAS_LIBRARIES ${GOTOBLAS_LIBRARIES} ${GFORTRAN_LIBRARY} )

MARK_AS_ADVANCED(
  GOTOBLAS_LIBRARIES
  GOTOBLAS_FOUND
  )