"""Script generated by PythonScriptDraw2DCurves."""
import numpy as np
import matplotlib.pyplot as plt


v_x = [0,1,2,3,4,5,6,7,8,9];
v_y = [-0.329554,0.536459,-0.444451,0.10794,-0.0452059,0.257742,-0.270431,0.0268018,0.904459,0.83239];
plt.plot(v_x,v_y,'--',label='v');

v2_x = [0,1,2,3,4,5,6,7,8,9];
v2_y = [0.271423,0.434594,-0.716795,0.213938,-0.967399,-0.514226,-0.725537,0.608354,-0.686642,-0.198111];
plt.plot(v2_x,v2_y,label='v2');
plt.show()